package pers.xym.fx.domain;

public class AdministratorRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fx_administrator_role.admin_id
	 * @mbg.generated  Wed Aug 09 11:45:24 GMT+08:00 2017
	 */
	private Integer adminId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fx_administrator_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:24 GMT+08:00 2017
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fx_administrator_role.admin_id
	 * @return  the value of fx_administrator_role.admin_id
	 * @mbg.generated  Wed Aug 09 11:45:24 GMT+08:00 2017
	 */
	public Integer getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fx_administrator_role.admin_id
	 * @param adminId  the value for fx_administrator_role.admin_id
	 * @mbg.generated  Wed Aug 09 11:45:24 GMT+08:00 2017
	 */
	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fx_administrator_role.role_id
	 * @return  the value of fx_administrator_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:24 GMT+08:00 2017
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fx_administrator_role.role_id
	 * @param roleId  the value for fx_administrator_role.role_id
	 * @mbg.generated  Wed Aug 09 11:45:24 GMT+08:00 2017
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}