package pers.xym.fx.domain;

public class AdministratorRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_permission.id
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_permission.name
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_permission.pid
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_permission.permission
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_permission.id
     *
     * @return the value of fx_permission.id
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_permission.id
     *
     * @param id the value for fx_permission.id
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_permission.name
     *
     * @return the value of fx_permission.name
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_permission.name
     *
     * @param name the value for fx_permission.name
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_permission.pid
     *
     * @return the value of fx_permission.pid
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_permission.pid
     *
     * @param pid the value for fx_permission.pid
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_permission.permission
     *
     * @return the value of fx_permission.permission
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_permission.permission
     *
     * @param permission the value for fx_permission.permission
     *
     * @mbg.generated Wed Aug 09 11:43:48 GMT+08:00 2017
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }
}