package pers.xym.fx.domain;

import java.math.BigDecimal;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_goods.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_goods.name
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_goods.num
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_goods.price
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_goods.tags
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_goods.deleted
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_goods.id
     *
     * @return the value of fx_goods.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_goods.id
     *
     * @param id the value for fx_goods.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_goods.name
     *
     * @return the value of fx_goods.name
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_goods.name
     *
     * @param name the value for fx_goods.name
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_goods.num
     *
     * @return the value of fx_goods.num
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_goods.num
     *
     * @param num the value for fx_goods.num
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_goods.price
     *
     * @return the value of fx_goods.price
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_goods.price
     *
     * @param price the value for fx_goods.price
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_goods.tags
     *
     * @return the value of fx_goods.tags
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_goods.tags
     *
     * @param tags the value for fx_goods.tags
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_goods.deleted
     *
     * @return the value of fx_goods.deleted
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_goods.deleted
     *
     * @param deleted the value for fx_goods.deleted
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}