package pers.xym.fx.domain;

public class RolePermissionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_role_permission.role_id
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_role_permission.permission_id
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_role_permission.role_id
     *
     * @return the value of fx_role_permission.role_id
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_role_permission.role_id
     *
     * @param roleId the value for fx_role_permission.role_id
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_role_permission.permission_id
     *
     * @return the value of fx_role_permission.permission_id
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_role_permission.permission_id
     *
     * @param permissionId the value for fx_role_permission.permission_id
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}