package pers.xym.fx.domain;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_tag.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_tag.name
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_tag.id
     *
     * @return the value of fx_tag.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_tag.id
     *
     * @param id the value for fx_tag.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_tag.name
     *
     * @return the value of fx_tag.name
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_tag.name
     *
     * @param name the value for fx_tag.name
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}