package pers.xym.fx.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.wxid
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private String wxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.nickname
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.avatar
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.pid
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.ban
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Boolean ban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.money
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Long money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.c1
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer c1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.c2
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer c2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user.c3
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer c3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.id
     *
     * @return the value of fx_user.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.id
     *
     * @param id the value for fx_user.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.wxid
     *
     * @return the value of fx_user.wxid
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.wxid
     *
     * @param wxid the value for fx_user.wxid
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setWxid(String wxid) {
        this.wxid = wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.nickname
     *
     * @return the value of fx_user.nickname
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.nickname
     *
     * @param nickname the value for fx_user.nickname
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.avatar
     *
     * @return the value of fx_user.avatar
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.avatar
     *
     * @param avatar the value for fx_user.avatar
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.pid
     *
     * @return the value of fx_user.pid
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.pid
     *
     * @param pid the value for fx_user.pid
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.ban
     *
     * @return the value of fx_user.ban
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Boolean getBan() {
        return ban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.ban
     *
     * @param ban the value for fx_user.ban
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setBan(Boolean ban) {
        this.ban = ban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.money
     *
     * @return the value of fx_user.money
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.money
     *
     * @param money the value for fx_user.money
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.c1
     *
     * @return the value of fx_user.c1
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.c1
     *
     * @param c1 the value for fx_user.c1
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setC1(Integer c1) {
        this.c1 = c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.c2
     *
     * @return the value of fx_user.c2
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getC2() {
        return c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.c2
     *
     * @param c2 the value for fx_user.c2
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setC2(Integer c2) {
        this.c2 = c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user.c3
     *
     * @return the value of fx_user.c3
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getC3() {
        return c3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user.c3
     *
     * @param c3 the value for fx_user.c3
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setC3(Integer c3) {
        this.c3 = c3;
    }
}