package pers.xym.fx.domain;

public class WalletLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_walletlog.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_walletlog.money
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Long money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_walletlog.user_id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_walletlog.memo
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_walletlog.id
     *
     * @return the value of fx_walletlog.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_walletlog.id
     *
     * @param id the value for fx_walletlog.id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_walletlog.money
     *
     * @return the value of fx_walletlog.money
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_walletlog.money
     *
     * @param money the value for fx_walletlog.money
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_walletlog.user_id
     *
     * @return the value of fx_walletlog.user_id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_walletlog.user_id
     *
     * @param userId the value for fx_walletlog.user_id
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_walletlog.memo
     *
     * @return the value of fx_walletlog.memo
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_walletlog.memo
     *
     * @param memo the value for fx_walletlog.memo
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}