package pers.xym.fx.dao;

import pers.xym.fx.domain.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_permission
     *
     * @mbg.generated Mon Aug 07 14:34:38 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_permission
     *
     * @mbg.generated Mon Aug 07 14:34:38 GMT+08:00 2017
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_permission
     *
     * @mbg.generated Mon Aug 07 14:34:38 GMT+08:00 2017
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_permission
     *
     * @mbg.generated Mon Aug 07 14:34:38 GMT+08:00 2017
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_permission
     *
     * @mbg.generated Mon Aug 07 14:34:38 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_permission
     *
     * @mbg.generated Mon Aug 07 14:34:38 GMT+08:00 2017
     */
    int updateByPrimaryKey(Permission record);
}