package pers.xym.fx.dao;

import pers.xym.fx.domain.RolePermissionKey;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_role_permission
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_role_permission
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_role_permission
     *
     * @mbg.generated Wed Aug 09 11:24:01 GMT+08:00 2017
     */
    int insertSelective(RolePermissionKey record);
}