package pers.xym.fx.dao;

import pers.xym.fx.domain.Tag;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_tag
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_tag
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_tag
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_tag
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    Tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_tag
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_tag
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int updateByPrimaryKey(Tag record);
}