package pers.xym.fx.dao;

import pers.xym.fx.domain.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user
     *
     * @mbg.generated Wed Aug 02 15:20:08 GMT+08:00 2017
     */
    int updateByPrimaryKey(User record);
}